### POST request to create a new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name": "Popescuu Ion",
    "email": "newEmail@yahoo.com",
    "address": "Adress 20 1423",
    "dateOfBirth": "1995-12-20",
    "registeredDate": "1999-01-20"
}
###