### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name": "Popescu Ion",
    "email": "pop.ion1@jahoo.com",
    "address": "my address 20",
    "dateOfBirth": "1995-12-20",
    "registeredDate": "1999-01-20",
    "Gender": "male"
}
###j