### PUT request to update a patient entity
PUT http://localhost:4000/patients/cf6c949a-2907-484f-b243-e28d8eae4f50
Content-Type: application/json

{
  "name": "Popescu Ion",
  "email": "sophia.clark@example.com",
  "address": "my address 20",
  "dateOfBirth": "1995-12-20"
}

###