### PUT request to update a patient entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174001
Content-Type: application/json

{
  "name": "Popescu Ion",
  "email": "myEmail24@yahoo.com",
  "address": "my address 20",
  "dateOfBirth": "1995-12-20"
}

###